= Cheatsheets

[[AccessLogOptions]]
== AccessLogOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`@enabled`|`Boolean`|+++
Sets if logging access to the Knot.x HTTP server is enabled or not. Default is enabled
 ('true')
+++
|[[format]]`@format`|`link:enums.html#LoggerFormat[LoggerFormat]`|+++
Set format of access log. Default is <strong>LoggerFormat.DEFAULT</strong>. Available values
 are:
 <ul>
   <li>DEFAULT
      <i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>
   </li>
   <li>SHORT
      <i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
   </li>
   <li>TINY
      <i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
   </li>
 </ul>
+++
|[[immediate]]`@immediate`|`Boolean`|+++
Configure when to collect access log. True if after request arrives, false after sending
 response.
+++
|===

[[AuthHandlerOptions]]
== AuthHandlerOptions

++++
 Handler definition that contains  name and JSON configuration. During
 link deployment all implementations of  are loaded from the classpath and based on  are initiated.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets link configuration.
+++
|[[factory]]`@factory`|`String`|+++
Sets  name
+++
|[[schema]]`@schema`|`String`|+++
Sets security schema name
+++
|===

[[BodyHandlerOptions]]
== BodyHandlerOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[fileUploadDirectory]]`@fileUploadDirectory`|`String`|+++
Set the location on Knot.x environment when uploaded files will be stored. These must be an
 absolute path.
+++
|[[fileUploadLimit]]`@fileUploadLimit`|`Number (Long)`|+++
Set the file upload limit in bytes
+++
|===

[[CSRFOptions]]
== CSRFOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[cookieName]]`@cookieName`|`String`|+++
Set the name of the CSRF cookie
+++
|[[cookiePath]]`@cookiePath`|`String`|+++
Set of the path of the CSRF cookie
+++
|[[headerName]]`@headerName`|`String`|+++
Set the CSRF token header name
+++
|[[secret]]`@secret`|`String`|+++
Set the secret used to generate CSRF token
+++
|[[timeout]]`@timeout`|`Number (long)`|+++
Set the timeout of the CSRF token
+++
|===

[[DropRequestOptions]]
== DropRequestOptions

++++
 Describes Knot.x HTTP Server dropping request options
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[backpressureBufferCapacity]]`@backpressureBufferCapacity`|`Number (long)`|+++
Sets the backpressure buffer capacity, the number of request that single Server instance can
 support concurrently. Default value is 1000.
+++
|[[backpressureStrategy]]`@backpressureStrategy`|`link:enums.html#BackpressureOverflowStrategy[BackpressureOverflowStrategy]`|+++
Sets the strategy how to deal with backpressure buffer overflow. Default is DROP_LATEST.

 Available values:
 <ul>
 <li>ERROR - terminates the whole sequence</li>
 <li>DROP_OLDEST - drops the oldest value from the buffer</li>
 <li>DROP_LATEST - drops the latest value from the buffer</li>
 </ul>
+++
|[[dropRequestResponseCode]]`@dropRequestResponseCode`|`Number (int)`|+++
Sets the HTTP response code returned wheb request is dropped. Default is
 TOO_MANY_REQUESTS(429)
+++
|[[enabled]]`@enabled`|`Boolean`|+++
Enabled/disables request dropping (backpressure) on heavy load. Default is true - enabled.
+++
|===

[[KnotxServerOptions]]
== KnotxServerOptions

++++
 Describes a Knot.x HTTP Server configuration
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[accessLog]]`@accessLog`|`link:dataobjects.html#AccessLogOptions[AccessLogOptions]`|+++
Set the access log options
+++
|[[displayExceptionDetails]]`@displayExceptionDetails`|`Boolean`|+++
Set whether to display or not the exception on error pages
+++
|[[dropRequestOptions]]`@dropRequestOptions`|`link:dataobjects.html#DropRequestOptions[DropRequestOptions]`|+++
Set the drop request options
+++
|[[routingOperations]]`@routingOperations`|`Array of link:dataobjects.html#RoutingOperationOptions[RoutingOperationOptions]`|+++
Set list of link.
+++
|[[routingSpecificationLocation]]`@routingSpecificationLocation`|`String`|+++
Location of your spec. It can be an absolute path, a local path or remote url (with HTTP
 protocol).
+++
|[[securityHandlers]]`@securityHandlers`|`Array of link:dataobjects.html#AuthHandlerOptions[AuthHandlerOptions]`|+++
Set list of link.
+++
|[[serverOptions]]`@serverOptions`|`link:dataobjects.html#HttpServerOptions[HttpServerOptions]`|+++
Set the HTTP Server options
+++
|===

[[RoutingHandlerOptions]]
== RoutingHandlerOptions

++++
 Handler definition that contains  name and JSON configuration.
 During link deployment all implementations of  are loaded from the classpath and based on  are initiated.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets link configuration.
+++
|[[name]]`@name`|`String`|+++
Sets  name
+++
|===

[[RoutingOperationOptions]]
== RoutingOperationOptions

++++
 Routing operation settings that define handlers / error handlers taking part in HTTP request
 processing. link loads link containing Open API specification which
 describes all endpoints with request / response schemas. Each endpoint defines operationId used
 in link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[failureHandlers]]`@failureHandlers`|`Array of link:dataobjects.html#RoutingHandlerOptions[RoutingHandlerOptions]`|+++
Sets list of error handlers definitions for particular operationId.
+++
|[[handlers]]`@handlers`|`Array of link:dataobjects.html#RoutingHandlerOptions[RoutingHandlerOptions]`|+++
Sets list of handlers definitions for particular operationId.
+++
|[[operationId]]`@operationId`|`String`|+++
Sets operationId name.
+++
|===

